name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from (leave empty to use current branch)'
        required: false
        default: ''
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Display deployment info
      run: |
        echo "Deploying from branch: ${{ github.event.inputs.branch || github.ref_name }}"
        echo "Triggered by: ${{ github.event_name }}"
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Create environment file
      working-directory: ./frontend
      env:
        WEB3FORMS_ACCESS_KEY: ${{ secrets.WEB3FORMS_ACCESS_KEY }}
      run: |
        echo "VITE_SHOW_PRICING=false" > .env
        echo "VITE_WEB3FORMS_ACCESS_KEY=${WEB3FORMS_ACCESS_KEY}" >> .env
        echo "Environment file created:"
        echo "VITE_SHOW_PRICING=$(grep VITE_SHOW_PRICING .env | cut -d'=' -f2)"
        echo "VITE_WEB3FORMS_ACCESS_KEY is set: $([ -n "${WEB3FORMS_ACCESS_KEY}" ] && echo 'YES' || echo 'NO')"

    - name: Build
      working-directory: ./frontend
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
